### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by adgbu** [nathonius/obsidian-trello#67]
When I try to install the Trello plugin in Obsidian it does not work and I get the error message:

> Failed to install plugin "Trello"

The vault is a new, mostly empty vault.

Trello Plugin version: 2.3.1
Obsidian version: 1.7.7 (Installer 1.7.7)
macOS version: Sonoma 14.6.1, Apple M1

**Comment by ChrisChinchilla** [comment]
@adgbu I think I didn't release 2.3.1 properly, I just tested 2.3.2 on a fresh vault and it works now.
